name: Print Message

on:
  push:
    branches:
      - main
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a Message
        run: echo "Hello! A Push detected on Main/Master Branch"

      - name: Print a Second Message
        run: echo "Hello! A Second Push detected on Main/Master Branch"